### ISSUE TITLE
could you generate curio_tracker.json file for some area expansion mods please?

### ISSUE THREAD

**Issue by MiloMccree** [Franisz/dd-curio-tracker#1]
I don't understand the codes at all, but I really want to make a mod to show items-to-curio interactions for some well known area extension mods.
[mod_curio_type_library.zip](https://github.com/Franisz/dd-curio-tracker/files/14896649/mod_curio_type_library.zip)
this zip concludes some curio_type_library.csv files.
could you please help me?

**Comment by Franisz** [comment]
I don't think this is enough. What mod is this from?

**Comment by MiloMccree** [comment]
The Sunward Isles (New Dungeon): https://steamcommunity.com/sharedfiles/filedetails/?id=1689234891
Sunward Expansion: The Night Parade: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2115544857
The Mountain - Updated Version:
https://steamcommunity.com/sharedfiles/filedetails/?id=2279458041
Vermintide Mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=2683922974

**Comment by Franisz** [comment]
[DarkestDungeon+4mods.zip](https://github.com/Franisz/dd-curio-tracker/files/14896896/DarkestDungeon%2B4mods.zip)
This should work, but I would use it only if using all 4 of these expansions, since the file was generated for all those mods installed together.

**Comment by MiloMccree** [comment]
Thank you so much!!! : )
