### ISSUE TITLE
badly written readme...

### ISSUE THREAD

**Issue by YokujinKaze** [Franisz/dd-curio-tracker#2]
you arent telling your average steam players which dependencies are needed to even execute anything written in the readme
how do you execute "$ npm install"? install what? the syntax isnt even complete
i sit here for an hour and havent even done step 1

**Comment by Franisz** [comment]
No? This is dev setup, use [Steam Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=2806761466) mod or install manually from [releases](https://github.com/Franisz/dd-curio-tracker/releases).

**Comment by YokujinKaze** [comment]
i was hoping i could generate my own tracker.json with some fixes, i believe some curio cleansings uses arent assigned correctly

**Comment by Franisz** [comment]
Then follow the readme, it's a simple node setup. 
- [An introduction to the npm package manager](https://nodejs.org/en/learn/getting-started/an-introduction-to-the-npm-package-manager#an-introduction-to-the-npm-package-manager)

**Comment by YokujinKaze** [comment]
i give up with the node nonsense, npm uninstalls itself everytime
